export const ROULETTE_DATA = [
  { id: 0, option: "0", style: { backgroundColor: "#0F0", textColor: "#000" } },
  { id: 1, option: "32", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 2, option: "15", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 3, option: "19", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 4, option: "4", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 5, option: "21", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 6, option: "2", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 7, option: "25", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 8, option: "17", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 9, option: "34", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 10, option: "27", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 11, option: "13", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 12, option: "36", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 13, option: "11", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 14, option: "30", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 15, option: "8", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 16, option: "23", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 17, option: "10", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 18, option: "5", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 19, option: "24", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 20, option: "16", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 21, option: "33", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 22, option: "1", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 23, option: "20", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 24, option: "14", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 25, option: "31", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 26, option: "9", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 27, option: "22", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 28, option: "18", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 29, option: "29", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 30, option: "7", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 31, option: "28", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 32, option: "12", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 33, option: "35", style: { backgroundColor: "#000", textColor: "#FFF" } },
  { id: 34, option: "3", style: { backgroundColor: "#F00", textColor: "#FFF" } },
  { id: 35, option: "26", style: { backgroundColor: "#000", textColor: "#FFF" } },
]

export const convertIdtoOption = function (id) {
  return ROULETTE_DATA.find((r) => r.id === id)?.option
}
